# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
